language: node_js
# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

templates: &template-script
  - echo "common-script1"
  - echo "common-script 2"
  - echo "common-script 3"

jobs:
  - name: sample-job-A
    type: runSh
    steps:
      - TASK:
          script:
            - echo "This is job A"
            - *template-script
            - echo "some more scripts"
